/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from 'react';
import { GroupProps, useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import { SkinnedMesh, BufferGeometry, Vector3 } from 'three';

const modelPath = require('../assets/models/avatar.glb');

type GLTF = ReturnType<typeof useGLTF> & { nodes: any; materials: any; animations: any };

type MousePosition = {
  mousePosition: {
    x: number;
    y: number;
  };
}

type WindowDimensions = {
  width: number;
  height: number;
}

export const Model: React.FC<GroupProps & MousePosition & WindowDimensions> = ({ ...props }) => {
  const { nodes, materials } = useGLTF(modelPath) as GLTF;
  const leftEye = useRef<SkinnedMesh<BufferGeometry>>(null);
  const rightEye = useRef<SkinnedMesh<BufferGeometry>>(null);
  const head = useRef<SkinnedMesh<BufferGeometry>>(null);
  const hair = useRef<SkinnedMesh<BufferGeometry>>(null);
  const glasses = useRef<SkinnedMesh<BufferGeometry>>(null);
  const teeth = useRef<SkinnedMesh<BufferGeometry>>(null);
  const top = useRef<SkinnedMesh<BufferGeometry>>(null);

  useFrame(() => {
    const { x: mouseX, y: mouseY } = props.mousePosition;
    const { width, height } = props;

    const x = (mouseX / width) - 0.5;
    const y = ((1 - (mouseY / height)) * 3) - 2.5;
 
    leftEye.current?.lookAt(new Vector3(x, y, 5));
    rightEye.current?.lookAt(new Vector3(x, y, 5));
    head.current?.lookAt(new Vector3(x, y, 5));
    hair.current?.lookAt(new Vector3(x, y, 5));
    glasses.current?.lookAt(new Vector3(x, y, 5));
    teeth.current?.lookAt(new Vector3(x, y, 5));
    top.current?.lookAt(new Vector3(x, y, 5));
  });

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      {/* <primitive object={new AxesHelper(2)} /> */}
      <mesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        ref={teeth}
      />
      <mesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
      />
      <mesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        ref={glasses}
      />
      <mesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
      />
      <mesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        ref={leftEye}
      />
      <mesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        ref={rightEye}
      />
      <mesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        ref={top}
      />
      <mesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        ref={hair}
      />
      <mesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
      />
      <mesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        ref={head}
      />
    </group>
  );
}

useGLTF.preload('/avatar.glb');
